apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  image: "vectorized/redpanda"
  version: "latest"
  replicas: 3
  externalConnectivity: true
  externalDNSSubdomain: vectorized.cloud
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
      port: 9092
    admin:
      port: 9644
    developerMode: true
