# permissions for end users to view redpandaclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redpandacluster-viewer-role
rules:
- apiGroups:
  - core.vectorized.io
  resources:
  - redpandaclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.vectorized.io
  resources:
  - redpandaclusters/status
  verbs:
  - get
