# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/vectorizedio/pre-commit-vectorizedio.git
  rev: 7f99e742d382f4a69e7854d2d3a32c2c01a2adc8
  hooks:
  - id: crlfmt
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
    args:
    - --allow-multiple-documents
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-symlinks
  - id: detect-private-key
- repo: https://github.com/dnephin/pre-commit-golang.git
  rev: master
  hooks:
  - id: go-mod-tidy
  - id: golangci-lint
  - id: go-vet
